chenged yml

diff --git a/.github/workflows/playwright-tests.yml b/.github/workflows/playwright-tests.yml
--- a/.github/workflows/playwright-tests.yml
+++ b/.github/workflows/playwright-tests.yml
@@ -30,6 +30,16 @@ jobs:
       - name: Run tests
         run: pytest -n 3 --alluredir=allure-results
 
+      - name: Generate Allure report
+        if: always()
+        run: |
+          if [ -d "allure-results" ]; then
+            npm run allure:generate
+          else
+            echo "allure-results directory not found"
+            exit 1
+          fi
+
       - name: Upload Allure report as artifact
         if: always()
         uses: actions/upload-artifact@v2
